name: Deploy Develop to Netlify
on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:  
  build-deploy:
    uses: ./.github/workflows/build-deploy.yml
    with:
      app_env: staging
      environment_main_branch: staging
      algolia_index_name: edb-docs-staging
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEVELOP_SITE_ID }}

