name: Deploy branch draft on Netlify
on:
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:  
  build-deploy:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'deploy') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    uses: EnterpriseDB/docs/.github/workflows/build-deploy.yml@a873eddc941859d882c2fe8ed9473fb9afd09d8e
    with:
      app_env: staging
      environment_main_branch: staging
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEVELOP_SITE_ID }}
