name: Deploy Main to Netlify
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: ./.github/workflows/build-deploy.yml
    with:
      app_env: production
      environment_main_branch: main
      algolia_index_name: edb-docs
      gtm_id: GTM-5W8M67
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEVELOP_SITE_ID }}
